name: Run Deploy
on:
  push:
    branches:    
      - master

jobs:
  build:
    name: Dispatch to deploy
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: hexlet-ci-cd-deploy-app
          owner: strelov1
          event_type: deploy
